### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by David-Prelinger** [familytree365/laravel-gedcom#50]
After importing a gedcom file (by command line), I received folllowing error:

`Class "Gedcom\Parser\Head\Parser\Head\Sour\Corp" not found

  at vendor/familytree365/php-gedcom/src/Parser/Head/Sour.php:52
     48▕                 case 'NAME':
     49▕                     $source->setName(trim($record[2]));
     50▕                     break;
     51▕                 case 'CORP':
  ➜  52▕                     $corp = Parser\Head\Sour\Corp::parse($parser);
     53▕                     $source->setCorp($corp);
     54▕                     break;
     55▕                 case 'DATA':
     56▕                     $data = Parser\Head\Sour\Data::parse($parser);

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
`

**Comment by curtisdelicata** [comment]
Should now be fixed.
